### ISSUE TITLE
Update examples to use ES modules and typescript js doc comments

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#843]
### Problem

Examples need to be run for each release and there is no easy way to type check JS.

### Solution

Use ES modules for examples to make easy to tell if examples use outdated API 

### Task List

 - [x] account-alias.js
 - [x] consensus-pub-sub.js
 - [x] create-account.js
 - [x] create-simple-contract.js
 - [x] create-stateful-contract.js
 - [x] create-topic.js
 - [x] delete-account.js
 - [x] file-append-chunked.js
 - [x] generate-key.js
 - [x] get-account-balance.js
 - [x] get-account-info.js
 - [x] multi-sig-offline.js
 - [x] scheduled-transaction-multi-sig-threshold.js
 - [x] sign-transaction.js
 - [x] transfer-tokens.js
 - [x] package.json

**Comment by danielakhterov** [comment]
Already fixed before today's release.
